apiVersion: v1
kind: Service
metadata:
  name: pulsechat-ws-gateway
  labels:
    app: pulsechat-ws-gateway
spec:
  type: {{ .Values.service.type }}
  selector:
    app: pulsechat-ws-gateway
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 4001
