apiVersion: v1
kind: Service
metadata:
  name: pulsechat-presence
  labels:
    app: pulsechat-presence
spec:
  type: {{ .Values.service.type }}
  selector:
    app: pulsechat-presence
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 4002
