apiVersion: v1
kind: Service
metadata:
  name: pulsechat-api
  labels:
    app: pulsechat-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: pulsechat-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 4000
