replicaCount: 1
image:
  repository: ghcr.io/sirvickky001/pulsechat-ws-gateway
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 4001
env:
  NODE_ENV: development
  API_URL: http://pulsechat-api:4000
  REDIS_URL: redis://redis:6379
  JWT_SECRET: dev-secret
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
