apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsechat-presence
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sirvickky001/pulsechat-config
    targetRevision: HEAD
    path: presence/chart
    helm:
      valueFiles:
        - ../production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pulsechat-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
